#![allow(dead_code)]
use anyhow::Result;
use fastembed::{TextEmbedding, InitOptions, EmbeddingModel};

/// Manages fastembed-rs integration for Local Context Memory
pub struct EmbeddingEngine {
    model: TextEmbedding,
}

impl EmbeddingEngine {
    pub fn new() -> Result<Self> {
        let cache_dir = std::path::PathBuf::from("/home/jane/.cache/fastembed");
        std::fs::create_dir_all(&cache_dir).ok();
        let options = InitOptions::new(EmbeddingModel::BGESmallENV15).with_cache_dir(cache_dir);
        let model = TextEmbedding::try_new(options)?;
        Ok(Self { model })
    }

    pub fn embed_text(&mut self, text: &str) -> Result<Vec<f32>> {
        let embeddings = self.model.embed(vec![text], None)?;
        
        if let Some(vector) = embeddings.into_iter().next() {
            Ok(vector)
        } else {
            anyhow::bail!("No embedding generated by fastembed.")
        }
    }
}
